name: Deploy to AWS EC2  # Nombre del flujo de trabajo

on:
  push:
    branches:
      - main  # Despliega solo cuando haya un push en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utiliza un entorno Ubuntu para ejecutar los comandos

    steps:
      - name: Checkout code  # Primer paso: obtener el código del repositorio
        uses: actions/checkout@v2

      - name: Set up SSH  # Segundo paso: configurar el acceso SSH para conectar con tu servidor EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY2 }}  # Aquí se utiliza una clave privada almacenada como secreto en GitHub

      - name: Deploy to server  # Tercer paso: ejecutar comandos para desplegar en el servidor EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-219-252-105.us-east-2.compute.amazonaws.com "cd /var/www/html/clinicpaws && sudo git pull origin main && sudo composer install --no-dev && sudo php artisan migrate --force && sudo php artisan config:cache && sudo php artisan route:cache && sudo php artisan view:cache"
